### ISSUE TITLE
Make this into a generic importer

### ISSUE THREAD

**Issue by dessalines** [rileynull/RedditLemmyImporter#1]
If this works correctly, there's no reason it can't be turned into a generic reddit -> lemmy historical importer. A couple things:

- [x] Rename the repo to something like reddit2lemmyimporter
- [x] Include the json as a separate repo
- [x] Give instructions for how to export a sub into that JSON format

**Comment by mesmere** [comment]
Yeah it seems that people might want to use this for other subreddits as well. I'll take the genzhou json file out of the repo and require it to be provided externally through a command line argument.

It looks like [this comment](https://lemmygrad.ml/post/187006/comment/130292) has some info on the export process, though it's not complete. Maybe I'll play around with the reddit json API and see if I can fill in the blanks and write up full instructions. No promises though

**Comment by dessalines** [comment]
Invite that person to this issue, they could probably write those instructions up for us, or create a separate repo for it.

**Comment by mesmere** [comment]
@dessalines All done. Sorry I didn't get around to working on any of these issues for so long. But they're done now. 

Btw I'm not going to be able to write code anymore. If anyone needs any more changes I think their best option is to fork, unfortunately.
